
logging:
  level:
    ROOT: DEBUG
    com.dxc.eproc: DEBUG
    
server:
  port: 9192

#Spring Starts
spring:
  jms:    listener:      auto-startup: false
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/catalogue_admin_service?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    #driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    #dbcp2:
      #test-on-borrow: true
  transaction:
    default-timeout: 1000    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.event.merge.entity_copy_observer: allow
        #hibernate.cache.use_second_level_cache: true
        #hibernate.cache.use_query_cache: false
        #hibernate.generate_statistics: false
      #hibernate.hbm2ddl.auto: update
#Spring Ends

#s3:
  #url: https://play.min.io
  #accessKey: Q3AM3UQ867SPQQA43P2F
  #accessSecret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

amqphub:
  amqp10jms:
    remote-url: amqp://127.0.0.1:5672


#eProcurement Properties Starts
eprocurement:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: false
    max-age: 1800
  #s3:
    #url: http:130.175.175.159:9000
    #accessKey: EPROCMINIOACCESS
    #accessSecret: EPROCMINIOSECRETACCESS    
    
# Feign Client Starts
master-service:
  url: http://localhost:9071
user-service:
  url: http://localhost:8181